#!/usr/bin/python

import os
import time

infile = "/tmp/in"
outfile = "/tmp/out"

def get(filename):
	if os.path.isfile(filename):
		return open(filename).read(10000)
	else:
		put(filename, "0")
		return "0"

def put(filename, data):
	f = open(filename, "w")
	f.write(data)
	f.close()

def getbw(data):
	for line in data.split("\n"):
		if "wlan0" in line or "eth0" in line or "en" in line:
			list = line.split()
			return (list[1], list[9])
	return (-1, -1)

data = get("/proc/net/dev")
input_prev = get(infile)
output_prev = get(outfile)
timediff = time.time()-os.path.getmtime(infile)
input, output = getbw(data)

print(  str( round((float(input)-float(input_prev))/1024/timediff*8) ) + "/" + str( round((float(output)-float(output_prev))/1024/timediff*8) ) + "K"  )

if timediff > 9.9:
	put(infile, input)
	put(outfile, output)
