#!/usr/bin/python

# calcsrtune 00:02:23,525-00:02:30,419 00:54:59,767-00:55:05,099 | read s m
# srtune -s $s -m $m sub.srt > sub_tuned.srt

from sys import argv
from datetime import datetime as dt

def seconds(t):
	return (dt.strptime(t, "%H:%M:%S,%f")-dt.strptime('00:00:00,0', "%H:%M:%S,%f")).total_seconds()

x1, y1 = map(seconds, argv[1].split('-'))
x2, y2 = map(seconds, argv[2].split('-'))
k = (y2-y1)/(x2-x1)
print(k, y1-k*x1)
