#!/bin/bash

git log --abbrev=6 --show-linear-break='' --topo-order --color=always --decorate=short --date=format-local:'%Y-%m-%d %H:%M' --format='%C(242)%ad  %C(148)%<(6,trunc)%h  %C(32)%<(20,trunc)%an %Creset%s%C(auto)%d  ―― %b' "$@" | gitlogfilter | less -FXSiRne
