#!/usr/bin/perl

if (!$ARGV[0]) {
	print "ntest address [port]\n";
	exit;
}

use IO::Socket;
use Time::HiRes('gettimeofday');

my $seconds = gettimeofday();

my $sock = new IO::Socket::INET (
	PeerAddr => $ARGV[0],
	PeerPort => $ARGV[1] || 80,
	Proto => 'tcp',
	Timeout => 10,
) or print "-1 $!\n";

if ($sock) { print gettimeofday()-$seconds."\n"; }
