#!/usr/bin/zsh

unsetopt CASE_MATCH

[[ $1 =~ "^https?://\S+\.(jpe?g|jfif|png|webp)($|\?|:)" ]] && exec feh ${1/dl=0/dl=1}
[[ $1 =~ "^https?://\S+\.pdf$" ]] && exec okular $1
[[ $1 =~ "^https?://(www\.|vm\.)?(youtu\.be|youtube\.com|tiktok\.com)" ]] && exec mpv $1
[[ $1 =~ "^https?://\S+\.(webm|mp4|avi|mov|mp3|m4a|og[ga])$" ]] && exec mpv --force-window=yes $1
[[ $1 =~ "^https?://\S+\.gif($|\?)" ]] && exec mpv --loop $1

if pgrep -f 'qutebrowser '; then
	exec open_url_in_instance.sh "$@"
else
	pgrep firefox && firefox "$@"
fi
